### ISSUE TITLE
Handle Short EIDs Case insensitive

### ISSUE THREAD

**Issue by KlausKrebs** [telekom/nuSIM-Loader-Application#6]
If a short EID is loaded into the data base using lower case hex digits and the NusimAdapter looks for the same EID in upper case hex representation the LoaderApp responds with an error ‘EID not found’. Since both representations of the EID are equivalent the LoaderApp should handle short EIDs case insensitively.

**Comment by mschaefers** [comment]
There are some SQL statements that still dont search case insensitively
