### ISSUE TITLE
Server - DevKit communication implementation

### ISSUE THREAD

**Issue by Strauteka** [telekom/nuSIM-Loader-Application#7]
Hello!

Trying to wrap my head around.

Reviewed  ./nusimapp code and feels like it is missing some implementation of server <=> device via uart? communication?

Currently, as I understand from documentation and code:
I have to write my own communication extending NusimSimAdapter.java class.
As Java runs on jvm and implement communication with hardware could be complicated(strange).
Also:
```
//  "nusimSimAdapter": {
//    "adapterClass": "de.scoopgmbh.nusimapp.nusimsim.adapter.huawei.HuaweiNusimSimAdapter",
//    "serialPort": "/dev/ttyXRUSB0",
//    "baudRate": 9600,
//    "commandRetries": 3,
//    "commandTimeoutMs": 10000,
//    "commandRetryDelayMs": 500
//  },
```
Feels like you are hiding something. :) (huawei.HuaweiNusimSimAdapter class not exists in project structure)

There are few options I could guess:
1. I am missing something,
2. Implementation of communication with Devkit is out of this project scope,
3. other;

Summary:
Does this project has full support writing Module BG95 via uart / devKit?

`...and finally load them to the target devices are implemented according to the nuSIM technical specifications in combination with an elementary GUI.`

P.S. If I am heavily missing something, please provide me with good overall documentation! "Not really into manufacturing business" 

Thank you!

**Comment by mschaefers** [comment]
Hello,

first of all: You are right in assuming you have to write an implementation of NusimSimAdapter.java to implement communication with your hardware

The commented section you mentioned is the configuration part of such an implementation. The implementation was not contained in the initial commit of this project for legal reasons, but was added about two weeks ago. Thats probably why you didnt see it :) See https://github.com/telekom/nuSIM-Loader-Application/blob/main/nusimloader-plugin-huawei/src/main/java/de/scoopgmbh/nusimapp/nusimsim/adapter/huawei/HuaweiNusimSimAdapter.java

Hope that helps
Best regards,
Michael

**Comment by Strauteka** [comment]
Yes, examined old pull.
Thank you very much!
